# Generated by Django 4.2.3 on 2023-08-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dentist",
            fields=[
                ("ID_Dentist", models.IntegerField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("contactAddress", models.CharField(max_length=255)),
                ("contactNumber", models.CharField(max_length=20)),
                ("expertise", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                ("ID_Record", models.IntegerField(primary_key=True, serialize=False)),
                ("examinationDate", models.DateField()),
                ("examinationTime", models.IntegerField()),
                ("examinationRoom", models.CharField(max_length=255)),
                ("note", models.CharField(max_length=255)),
                (
                    "ID_Dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.dentist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("ID_Patient", models.IntegerField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("contactAddress", models.CharField(max_length=255)),
                ("contactNumber", models.CharField(max_length=20)),
                ("healthInsuranceNumber", models.CharField(max_length=50)),
                ("history", models.CharField(max_length=255)),
                (
                    "ID_Dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.dentist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("ID_Report", models.IntegerField(primary_key=True, serialize=False)),
                ("reportStyle", models.CharField(max_length=255)),
                ("reportDate", models.DateField()),
                ("totalAmount", models.FloatField()),
                ("note", models.CharField(max_length=255)),
                (
                    "ID_Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.patient",
                    ),
                ),
                (
                    "ID_Record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.healthrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["reportDate"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("ID_Service", models.IntegerField(primary_key=True, serialize=False)),
                ("serviceName", models.CharField(max_length=255)),
                ("serviceDescription", models.CharField(max_length=255)),
                ("cost", models.FloatField()),
                (
                    "ID_Report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("ID_Staff", models.IntegerField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("contactAddress", models.CharField(max_length=255)),
                ("contactNumber", models.CharField(max_length=20)),
                ("position", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Trong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ID_Record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.healthrecord",
                    ),
                ),
                (
                    "ID_Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="ID_Staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management_dental_clinic.staff",
            ),
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registerTime", models.CharField(max_length=255)),
                (
                    "ID_Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.patient",
                    ),
                ),
                (
                    "ID_Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="ID_Patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="management_dental_clinic.patient",
            ),
        ),
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ID_Dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertises",
                        to="management_dental_clinic.dentist",
                    ),
                ),
                (
                    "ID_Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DentistProcedure",
            fields=[
                (
                    "ID_Procedure",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("examinationDate", models.DateField()),
                ("examinationTime", models.IntegerField()),
                ("examinationRoom", models.CharField(max_length=255)),
                ("note", models.CharField(max_length=255)),
                (
                    "ID_Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookingStatus", models.IntegerField()),
                ("bookingDate", models.DateField()),
                ("bookingStyle", models.CharField(max_length=10)),
                ("note", models.CharField(max_length=255)),
                ("examinationTime", models.CharField(max_length=255)),
                (
                    "ID_Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.patient",
                    ),
                ),
                (
                    "ID_Procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_dental_clinic.dentistprocedure",
                    ),
                ),
            ],
        ),
    ]
