# Generated by Django 4.2.1 on 2023-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_dental_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['examinationDate']},
        ),
        migrations.AddField(
            model_name='dentist',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dentist',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='ID_Dentist',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ID_Patient',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
