# Generated by Django 4.2.1 on 2023-08-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_dental_clinic', '0002_alter_healthrecord_options_dentist_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='history',
            field=models.CharField(default='', max_length=255),
        ),
    ]
