# Generated by Django 4.2.1 on 2023-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_dental_clinic', '0006_remove_service_id_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ID_Service',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
