# Generated by Django 4.2.1 on 2023-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_dental_clinic', '0007_alter_service_id_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registerTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
